sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USER=rubenrivilla+microservices_school
  - DOCKER_PASSWORD=21NXV3D88NHL7JP2EX65AM1MNVTG2M3TTJTHFS1OV8L4CDSEMDALJPVYMHY4TKR6

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version

install: 
  - yarn install

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10

script:
  - make qa
  - make brand
  - make build

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker